routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('hpvs', 'HpvController');

app/Hpv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hpv extends Model
{
    protected $fillable = ['name', 'weight', 'height', 'length', 'width', 'trunk_volume'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HpvController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Hpv;

class HpvController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hpvs = Hpv::latest()->paginate(5);

        return view('hpvs.index',compact('hpvs'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hpvs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'weight' => 'required',
            'height' => 'required',
            'length' => 'required',
            'width' => 'required',
            'trunk_volume' => 'required'
        ]);

        Hpv::create($request->all());

        return redirect()->route('hpvs.index')
                ->with('success','Hpv created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  Hpv  $hpv
     * @return \Illuminate\Http\Response
     */
    public function show(Hpv $hpv)
    {
        return view('hpvs.show',compact('hpv'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Hpv  $hpv
     * @return \Illuminate\Http\Response
     */
    public function edit(Hpv $hpv)
    {
        return view('hpvs.edit',compact('hpv'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Hpv  $hpv
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hpv $hpv)
    {
        $request->validate([
            'name' => 'required',
            'weight' => 'required',
            'height' => 'required',
            'length' => 'required',
            'width' => 'required',
            'trunk_volume' => 'required'
        ]);

        $hpv->update($request->all());

        return redirect()->route('hpvs.index')
                ->with('success','Hpv updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Hpv  $hpv
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hpv $hpv)
    {
        $hpv->delete();

        return redirect()->route('hpvs.index')
            ->with('success','Hpv deleted successfully');

    }
}

resources/views/hpvs/create.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Hpv</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('hpvs.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('hpvs.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Weight:</strong>
                <input type="text" name="weight" class="form-control" placeholder="Weight">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Height:</strong>
                <input type="text" name="height" class="form-control" placeholder="Height">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Length:</strong>
                <input type="text" name="length" class="form-control" placeholder="Length">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Width:</strong>
                <input type="text" name="width" class="form-control" placeholder="Width">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Trunk volume:</strong>
                <input type="text" name="trunk_volume" class="form-control" placeholder="Trunk volume">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/hpvs/edit.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit hpv</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('hpvs.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('hpvs.update',$hpv->id) }}" method="POST">
        @csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        <input type="text" name="name" value="{{$hpv->name}}" class="form-control" placeholder="Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Weight:</strong>
                        <input type="text" name="weight" value="{{$hpv->weight}}" class="form-control" placeholder="Weight">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Height:</strong>
                        <input type="text" name="height" value="{{$hpv->height}}" class="form-control" placeholder="Height">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Length:</strong>
                        <input type="text" name="length" value="{{$hpv->length}}" class="form-control" placeholder="Length">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Width:</strong>
                        <input type="text" name="width" value="{{$hpv->width}}" class="form-control" placeholder="Width">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Trunk volume:</strong>
                        <input type="text" name="trunk_volume" value="{{$hpv->trunk_volume}}" class="form-control" placeholder="Trunk volume">
                    </div>
                </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/hpvs/index.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Hpv admin pannel</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('hpvs.create') }}">Create New hpv</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Weight</th>
            <th>Height</th>
            <th>Length</th>
            <th>Width</th>
            <th>Trunk volume</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($hpvs as $hpv)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $hpv->name }}</td>
            <td>{{ $hpv->weight }}</td>
            <td>{{ $hpv->height }}</td>
            <td>{{ $hpv->length }}</td>
            <td>{{ $hpv->width }}</td>
            <td>{{ $hpv->trunk_volume }}</td>
            <td>
                <form action="{{ route('hpvs.destroy',$hpv->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('hpvs.show',$hpv->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('hpvs.edit',$hpv->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    {!! $hpvs->links() !!}
@endsection

resources/views/hpvs/show.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show hpv</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('hpvs.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{$hpv->name}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Weight:</strong>
                {{$hpv->weight}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Height:</strong>
                {{$hpv->height}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Length:</strong>
                {{$hpv->length}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Width:</strong>
                {{$hpv->width}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Trunk volume:</strong>
                {{$hpv->trunk_volume}}
            </div>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
  	<meta charset="UTF-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<meta http-equiv="X-UA-Compatible" content="ie=edge">
  	<title>Hpv technical informations website</title>
  	<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  	<div class="container">
    	@yield('content')
  	</div>
  	<script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>